name: pnp
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - attr=2.5.1
  - blas=2.131
  - blas-devel=3.9.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.7.14
  - cffi=1.17.1
  - cycler=0.12.1
  - dcm2niix=1.0.20250506
  - fftw=3.3.10
  - freetype=2.13.3
  - lcms2=2.17
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.71
  - libcblas=3.9.0
  - libdeflate=1.22
  - libevent=2.1.12
  - libfabric=2.1.0
  - libfabric1=2.1.0
  - libffi=3.4.4
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.0
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libhwloc=2.11.2
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnl=3.11.0
  - libnsl=2.0.1
  - libopenblas=0.3.29
  - libpmix=5.0.8
  - libpng=1.6.50
  - libsqlite=3.45.2
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=256.9
  - libtiff=4.7.0
  - libudev1=257.4
  - libuuid=2.38.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxml2=2.13.5
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - matplotlib-base=3.10.3
  - mpi=1.0
  - mpi4py=4.0.3
  - munkres=1.1.4
  - ncurses=6.4
  - numpy=1.24.4
  - openblas=0.3.29
  - openjpeg=2.5.3
  - openmpi=5.0.7
  - openssl=3.5.1
  - patsy=1.0.1
  - pip=25.1.1
  - pooch=1.8.2
  - pthread-stubs=0.4
  - pycparser=2.21
  - pynfft=1.3.2
  - pysocks=1.7.1
  - python=3.10.13
  - python-tzdata=2025.2
  - python_abi=3.10
  - qhull=2020.2
  - rdma-core=55.0
  - readline=8.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - sqlite=3.45.2
  - statsmodels=0.14.5
  - tk=8.6.13
  - ucc=1.3.0
  - ucx=1.18.0
  - unicodedata2=16.0.0
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - albumentations==0.4.3
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - astropy==6.0.1
      - astropy-iers-data==0.2024.4.1.0.33.14
      - asttokens==2.4.1
      - async-timeout==4.0.3
      - attrs==23.2.0
      - beautifulsoup4==4.13.4
      - blobfile==2.1.1
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - clean-fid==0.1.35
      - click==8.1.7
      - clip==1.0
      - comm==0.2.2
      - contourpy==1.2.0
      - cython==3.0.8
      - debugpy==1.8.0
      - decorator==5.1.1
      - deepinv==0.1.1
      - docker-pycreds==0.4.0
      - ehtim==1.2.7
      - ehtplot==0.9.0
      - einops==0.7.0
      - ema-pytorch==0.7.7
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - filelock==3.9.0
      - flash-attn==2.0.8
      - fonttools==4.49.0
      - frozenlist==1.4.1
      - fsspec==2023.5.0
      - ftfy==6.1.3
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - gdown==5.2.0
      - gitdb==4.0.11
      - gitpython==3.1.42
      - h5py==3.10.0
      - hdf5storage==0.1.19
      - hdrhistogram==0.10.3
      - huggingface-hub==0.20.3
      - hydra-core==1.3.2
      - idna==3.4
      - imageio==2.34.0
      - imgaug==0.2.6
      - iniconfig==2.0.0
      - iopath==0.1.10
      - ipykernel==6.29.4
      - ipython==8.23.0
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==0.14.0
      - jplephem==2.21
      - jupyter-client==8.6.1
      - jupyter-core==5.7.2
      - kiwisolver==1.4.5
      - lazy-loader==0.3
      - lightning-utilities==0.10.1
      - lmdb==1.4.1
      - loralib==0.1.2
      - lxml==4.9.4
      - markupsafe==2.1.3
      - matplotlib==3.8.3
      - matplotlib-inline==0.1.7
      - monai==1.3.0
      - mpmath==1.3.0
      - multidict==6.0.5
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - nfft==0.1
      - ninja==1.11.1.1
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.9.41
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - opencv-python-headless==4.9.0.80
      - packaging==23.2
      - pandas==1.5.3
      - pandas-appender==0.9.8.4
      - paramsurvey==0.4.19
      - parso==0.8.4
      - pbr==6.0.0
      - pdfkit==1.0.0
      - pexpect==4.9.0
      - pillow==10.2.0
      - piq==0.7.0
      - platformdirs==4.2.0
      - pluggy==1.5.0
      - portalocker==2.8.2
      - prdc==0.2
      - prompt-toolkit==3.0.43
      - protobuf==4.25.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycryptodomex==3.20.0
      - pydicom==3.0.1
      - pyerfa==2.0.1.2
      - pygments==2.17.2
      - pylops==2.2.0
      - pyparsing==3.1.1
      - pytest==8.2.0
      - python-dateutil==2.8.2
      - pytorch-lightning==2.2.1
      - pytz==2024.1
      - pywavelets==1.5.0
      - pyyaml==6.0.1
      - pyzmq==26.0.1
      - regex==2023.12.25
      - requests==2.28.1
      - safetensors==0.4.2
      - scikit-image==0.22.0
      - scikit-learn==1.0.2
      - scipy==1.12.0
      - sentry-sdk==1.40.6
      - setproctitle==1.3.3
      - setuptools==80.4.0
      - sgp4==2.23
      - six==1.16.0
      - skyfield==1.48
      - smmap==5.0.1
      - soupsieve==2.7
      - stack-data==0.6.3
      - sympy==1.12
      - tabulate==0.9.0
      - taming-transformers==0.0.1
      - termcolor==2.4.0
      - threadpoolctl==3.3.0
      - tifffile==2024.2.12
      - tomli==2.0.1
      - torch==2.1.0
      - torch-fidelity==0.3.0
      - torchaudio==2.1.0
      - torchmetrics==1.3.1
      - torchvision==0.16.0
      - tornado==6.4
      - tqdm==4.66.1
      - traitlets==5.14.3
      - triton==2.1.0
      - typing-extensions==4.8.0
      - tzdata==2024.1
      - urllib3==1.26.13
      - wandb==0.16.3
      - wcwidth==0.2.13
      - yacs==0.1.8
      - yarl==1.9.4
prefix: /home/yhu160/.conda/envs/pnp
